# Generated by Django 4.2.7 on 2024-01-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='город'),
        ),
    ]
