# Generated by Django 4.2.7 on 2024-01-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_salon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_day',
            field=models.DateField(blank=True, null=True, verbose_name='день трудоустройства'),
        ),
    ]
