# Generated by Django 4.2.7 on 2024-01-28 11:15

from django.db import migrations, models
from django.utils import timezone


def fill_employee_default_emp_day(apps, schema_editor):
    Employee = apps.get_model('website', 'Employee')
    employees = Employee.objects.all()
    for employee in employees.iterator():
        employee.emp_day = timezone.now().date().isoformat()
        employee.save()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_employee_emp_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_day',
            field=models.DateField(default=timezone.now().date().isoformat(), verbose_name='день трудоустройства'),
        ),
        migrations.RunPython(fill_employee_default_emp_day),
    ]
